enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# included-patches = "'Custom branding'"
# excluded-patches = "'Swipe controls'"
# version = "auto"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

# [Music]
# build-mode = "both"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# version = "auto"
# arch = "arm64-v8a"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "auto"
included-patches = "'Change package name'"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
version = "10.49.0-release.0"
included-patches = "'Open links with app chooser' 'Change package name'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
included-patches = "'Change package name'"
